version: "3"

services:
  front:
    build: .
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/usr/src/app
      - ~/.aws/:/root/.aws/
    command: sh -c 'cd front && yarn start'
    ports:
      - 3000:3000
      - 20002:20002
    stdin_open: true
    tty: true
